// pages/app/Reports.jsx
import { useState, useEffect } from "react";
import { reportApi } from "../../api/reportApi";
import { saleApi } from "../../api/saleApi";
import { productApi } from "../../api/productApi";
import { customerApi } from "../../api/customerApi";
import { settingsApi } from "../../api/settingsApi";
import { Spinner } from "../../components/ui/Spinner";
import { Button } from "../../components/ui/Button";
import { SearchBar } from "../../components/ui/SearchBar";
import { formatCurrency } from "../../utils/formatCurrency";
import { formatDate, formatDateTime } from "../../utils/formatDate";
import {
  TrendingUp, Package, BarChart3, Users, Receipt, Printer, FileText,
} from "lucide-react";

const tabs = [
  { key: "overview", label: "Overview", icon: BarChart3 },
  { key: "general", label: "General", icon: FileText },
  { key: "inventory", label: "Inventory", icon: Package },
  { key: "transactions", label: "Transactions", icon: Receipt },
  { key: "customers", label: "Customers", icon: Users },
];

const ReportFooter = ({ businessName }) => (
  <div className="report-footer" style={{ marginTop: 24, paddingTop: 12, borderTop: "1px solid #e2e8f0", textAlign: "center", color: "#94a3b8", fontSize: 10 }}>
    <p>Generated by SmartPOS on {formatDate(new Date())} at {new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</p>
    <p>{businessName} — Confidential</p>
  </div>
);

export const Reports = () => {
  const [activeTab, setActiveTab] = useState("overview");
  const [period, setPeriod] = useState("today");
  const [salesData, setSalesData] = useState(null);
  const [inventoryData, setInventoryData] = useState(null);
  const [allSales, setAllSales] = useState([]);
  const [allProducts, setAllProducts] = useState([]);
  const [allCustomers, setAllCustomers] = useState([]);
  const [receiptSettings, setReceiptSettings] = useState({ receiptHeader: "" });
  const [loading, setLoading] = useState(true);
  const [salesSearch, setSalesSearch] = useState("");
  const [invSearch, setInvSearch] = useState("");
  const [custSearch, setCustSearch] = useState("");

  const fetchData = () => {
    setLoading(true);
    Promise.all([
      reportApi.getSales({ period }),
      reportApi.getInventory(),
      saleApi.getAll({ limit: 500 }),
      productApi.getAll({ limit: 500 }),
      customerApi.getAll({ limit: 500 }),
      settingsApi.getReceipt(),
    ]).then(([salesRes, invRes, allSalesRes, allProdRes, allCustRes, settingsRes]) => {
      if (salesRes.success) setSalesData(salesRes.data || salesRes);
      if (invRes.success) setInventoryData(invRes.data || invRes);
      if (allSalesRes.success) setAllSales(allSalesRes.data?.sales || allSalesRes.sales || []);
      if (allProdRes.success) setAllProducts(allProdRes.data?.products || allProdRes.products || []);
      if (allCustRes.success) setAllCustomers(allCustRes.data?.customers || allCustRes.customers || []);
      if (settingsRes.success) setReceiptSettings({ receiptHeader: (settingsRes.data || settingsRes).receiptHeader || "" });
    }).finally(() => setLoading(false));
  };

  useEffect(() => { fetchData(); }, [period]);

  const businessName = receiptSettings.receiptHeader?.split("\n")[0] || "SmartPOS";

  const handlePrint = (elementId) => {
    const content = document.getElementById(elementId)?.innerHTML;
    if (!content) return;
    const printWindow = window.open("", "", "width=900,height=600");
    printWindow.document.write(`
      <html><head><title>Report</title>
      <style>
        *{margin:0;padding:0;box-sizing:border-box;}
        body{font-family:'Segoe UI',Arial,sans-serif;font-size:12px;padding:24px;color:#1e293b;background:#fff;}
        .report-header{text-align:center;margin-bottom:20px;padding-bottom:16px;border-bottom:2px solid #2563eb;}
        .report-header h1{color:#2563eb;font-size:20px;margin:0 0 4px;}
        .report-header p{color:#64748b;font-size:11px;margin:0;}
        table{width:100%;border-collapse:collapse;margin:12px 0;border:1px solid #e2e8f0;}
        th{background:#f1f5f9;color:#475569;font-weight:600;padding:10px 12px;text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:0.5px;}
        td{padding:10px 12px;border-top:1px solid #e2e8f0;font-size:12px;}
        tr:nth-child(even){background:#f8fafc;}
        .text-right{text-align:right;}
        .text-center{text-align:center;}
        .font-mono{font-family:'Courier New',monospace;font-size:11px;}
        .text-green{color:#059669;font-weight:600;}
        .text-red{color:#dc2626;font-weight:600;}
        .text-yellow{color:#d97706;font-weight:600;}
        .text-blue{color:#2563eb;font-weight:600;}
        .text-purple{color:#7c3aed;font-weight:600;}
        .stat-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:12px;margin:16px 0;}
        .stat-card{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:14px 16px;}
        .stat-label{font-size:10px;color:#64748b;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:4px;}
        .stat-value{font-size:20px;font-weight:700;color:#1e293b;}
        .summary-row{background:#f1f5f9;font-weight:700;}
        .report-footer{margin-top:24px;padding-top:12px;border-top:1px solid #e2e8f0;text-align:center;color:#94a3b8;font-size:10px;}
        @media print{.no-print{display:none!important;}}
      </style></head>
      <body>${content}</body></html>
    `);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 300);
  };

  const totalRevenue = allSales.filter((s) => s.status === "completed").reduce((sum, s) => sum + (s.total || 0), 0);
  const inventoryValue = allProducts.reduce((sum, p) => sum + (p.price || 0) * (p.stock || 0), 0);
  const totalVat = allSales.filter((s) => s.status === "completed").reduce((sum, s) => sum + (s.vatAmount || 0), 0);
  const totalDiscounts = allSales.filter((s) => s.status === "completed").reduce((sum, s) => sum + (s.discount || 0), 0);
  const cashSales = allSales.filter((s) => s.paymentMethod === "cash" && s.status === "completed").reduce((sum, s) => sum + (s.total || 0), 0);
  const mpesaSales = allSales.filter((s) => s.paymentMethod === "mpesa" && s.status === "completed").reduce((sum, s) => sum + (s.total || 0), 0);
  const cardSales = allSales.filter((s) => s.paymentMethod === "card" && s.status === "completed").reduce((sum, s) => sum + (s.total || 0), 0);

  const filteredSales = salesSearch
    ? allSales.filter((s) => s.receiptNumber?.toLowerCase().includes(salesSearch.toLowerCase()) || s.customerName?.toLowerCase().includes(salesSearch.toLowerCase()))
    : allSales.filter((s) => s.status !== "held");
  const filteredInventory = invSearch
    ? allProducts.filter((p) => p.name.toLowerCase().includes(invSearch.toLowerCase()))
    : allProducts;
  const filteredCustomers = custSearch
    ? allCustomers.filter((c) => c.name?.toLowerCase().includes(custSearch.toLowerCase()) || c.phone?.includes(custSearch) || c.loyaltyCardNumber?.includes(custSearch))
    : allCustomers;

  if (loading) return <Spinner className="py-12" />;

  return (
    <div>
      <div className="flex items-center justify-between mb-6 no-print">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Reports</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Business insights and analytics</p>
        </div>
        <div className="flex gap-2">
          {activeTab === "overview" && ["today", "week", "month"].map((p) => (
            <button key={p} onClick={() => setPeriod(p)} className={`px-3 py-1.5 text-sm rounded-lg font-medium capitalize ${period === p ? "bg-primary-600 text-white" : "bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400"}`}>{p}</button>
          ))}
        </div>
      </div>

      <div className="flex gap-1 mb-6 border-b border-gray-200 dark:border-gray-700 overflow-x-auto no-print">
        {tabs.map((tab) => (
          <button key={tab.key} onClick={() => setActiveTab(tab.key)} className={`flex items-center gap-2 px-4 py-2 text-sm font-medium border-b-2 whitespace-nowrap transition-colors ${activeTab === tab.key ? "border-primary-600 text-primary-600" : "border-transparent text-gray-500 hover:text-gray-700"}`}>
            <tab.icon className="w-4 h-4" /> {tab.label}
          </button>
        ))}
      </div>

      {/* Overview */}
      {activeTab === "overview" && (
        <div>
          <div className="flex items-center justify-between mb-4 no-print">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white capitalize">{period} Overview</h2>
            <Button variant="outline" size="sm" onClick={() => handlePrint("report-overview")}><Printer className="w-4 h-4" /> Print</Button>
          </div>
          <div id="report-overview">
            <div className="report-header"><h1>{businessName}</h1><p>{period.charAt(0).toUpperCase() + period.slice(1)} Overview — {formatDate(new Date())}</p></div>
            <div className="stat-grid">
              <div className="stat-card"><div className="stat-label">Total Sales</div><div className="stat-value text-green">{formatCurrency(salesData?.totalSales || 0)}</div></div>
              <div className="stat-card"><div className="stat-label">Transactions</div><div className="stat-value text-blue">{salesData?.transactions || 0}</div></div>
              <div className="stat-card"><div className="stat-label">Avg Transaction</div><div className="stat-value">{formatCurrency(salesData?.averageTransaction || 0)}</div></div>
            </div>
            {salesData?.paymentMethods?.length > 0 && (
              <table><thead><tr><th>Payment Method</th><th className="text-right">Amount</th><th className="text-right">Count</th></tr></thead><tbody>
                {salesData.paymentMethods.map((pm) => <tr key={pm._id}><td className="capitalize">{pm._id}</td><td className="text-right">{formatCurrency(pm.total)}</td><td className="text-right">{pm.count}</td></tr>)}
              </tbody></table>
            )}
            <table><thead><tr><th>Inventory</th><th className="text-right">Count</th></tr></thead><tbody>
              <tr><td>Total Products</td><td className="text-right">{inventoryData?.totalProducts || 0}</td></tr>
              <tr><td>Low Stock</td><td className={`text-right ${inventoryData?.lowStockCount > 0 ? "text-yellow" : ""}`}>{inventoryData?.lowStockCount || 0}</td></tr>
              <tr><td>Out of Stock</td><td className={`text-right ${inventoryData?.outOfStockCount > 0 ? "text-red" : ""}`}>{inventoryData?.outOfStockCount || 0}</td></tr>
            </tbody></table>
            <ReportFooter businessName={businessName} />
          </div>
        </div>
      )}

      {/* General */}
      {activeTab === "general" && (
        <div>
          <div className="flex items-center justify-between mb-4 no-print">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">General Business Report</h2>
            <Button variant="outline" size="sm" onClick={() => handlePrint("report-general")}><Printer className="w-4 h-4" /> Print</Button>
          </div>
          <div id="report-general">
            <div className="report-header"><h1>{businessName}</h1><p>General Business Report — {formatDate(new Date())}</p></div>
            <div className="stat-grid">
              <div className="stat-card"><div className="stat-label">Total Revenue</div><div className="stat-value text-green">{formatCurrency(totalRevenue)}</div></div>
              <div className="stat-card"><div className="stat-label">Inventory Value</div><div className="stat-value text-purple">{formatCurrency(inventoryValue)}</div></div>
              <div className="stat-card"><div className="stat-label">Cash Sales</div><div className="stat-value">{formatCurrency(cashSales)}</div></div>
              <div className="stat-card"><div className="stat-label">M-Pesa Sales</div><div className="stat-value">{formatCurrency(mpesaSales)}</div></div>
              <div className="stat-card"><div className="stat-label">Card Sales</div><div className="stat-value">{formatCurrency(cardSales)}</div></div>
              <div className="stat-card"><div className="stat-label">Total VAT</div><div className="stat-value">{formatCurrency(totalVat)}</div></div>
              <div className="stat-card"><div className="stat-label">Total Discounts</div><div className="stat-value text-red">{formatCurrency(totalDiscounts)}</div></div>
              <div className="stat-card"><div className="stat-label">Customers</div><div className="stat-value text-blue">{allCustomers.length}</div></div>
              <div className="stat-card"><div className="stat-label">Products</div><div className="stat-value text-blue">{allProducts.length}</div></div>
            </div>
            <ReportFooter businessName={businessName} />
          </div>
        </div>
      )}

      {/* Inventory */}
      {activeTab === "inventory" && (
        <div>
          <div className="flex items-center justify-between mb-4 no-print">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Inventory Report</h2>
            <Button variant="outline" size="sm" onClick={() => handlePrint("report-inventory")}><Printer className="w-4 h-4" /> Print</Button>
          </div>
          <div className="mb-4 no-print"><SearchBar value={invSearch} onChange={setInvSearch} placeholder="Search products..." /></div>
          <div id="report-inventory">
            <div className="report-header"><h1>{businessName}</h1><p>Inventory Report — {formatDate(new Date())}</p></div>
            <table><thead><tr><th>Product</th><th className="text-right">Stock</th><th className="text-right">Price</th><th className="text-right">Cost</th><th className="text-right">Value</th></tr></thead><tbody>
              {filteredInventory.map((p) => (
                <tr key={p._id}><td>{p.name}</td><td className={`text-right ${p.stock <= 5 ? "text-red" : p.stock <= 10 ? "text-yellow" : ""}`}>{p.stock}</td><td className="text-right">{formatCurrency(p.price)}</td><td className="text-right">{formatCurrency(p.cost || 0)}</td><td className="text-right" style={{ fontWeight: 700 }}>{formatCurrency((p.price || 0) * (p.stock || 0))}</td></tr>
              ))}
            </tbody></table>
            <div className="stat-grid" style={{ marginTop: 16 }}><div className="stat-card"><div className="stat-label">Total Inventory Value</div><div className="stat-value text-purple">{formatCurrency(inventoryValue)}</div></div></div>
            <ReportFooter businessName={businessName} />
          </div>
        </div>
      )}

      {/* Transactions */}
      {activeTab === "transactions" && (
        <div>
          <div className="flex items-center justify-between mb-4 no-print">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Transactions Report</h2>
            <Button variant="outline" size="sm" onClick={() => handlePrint("report-transactions")}><Printer className="w-4 h-4" /> Print</Button>
          </div>
          <div className="mb-4 no-print"><SearchBar value={salesSearch} onChange={setSalesSearch} placeholder="Search by receipt or customer..." /></div>
          <div id="report-transactions">
            <div className="report-header"><h1>{businessName}</h1><p>Transactions Report — {formatDate(new Date())}</p></div>
            <table><thead><tr><th>Receipt</th><th>Customer</th><th className="text-right">Total</th><th className="text-center">Payment</th><th className="text-center">Status</th><th className="text-right">Date</th></tr></thead><tbody>
              {filteredSales.map((s) => (
                <tr key={s._id}><td className="font-mono">{s.receiptNumber}</td><td>{s.customerName || "—"}</td><td className="text-right" style={{ fontWeight: 700 }}>{formatCurrency(s.total)}</td><td className="text-center capitalize">{s.paymentMethod}</td><td className="text-center"><span className={s.status === "completed" ? "text-green" : "text-red"}>{s.status}</span></td><td className="text-right">{formatDateTime(s.createdAt)}</td></tr>
              ))}
            </tbody></table>
            <ReportFooter businessName={businessName} />
          </div>
        </div>
      )}

      {/* Customers */}
      {activeTab === "customers" && (
        <div>
          <div className="flex items-center justify-between mb-4 no-print">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">Customer Report</h2>
            <Button variant="outline" size="sm" onClick={() => handlePrint("report-customers")}><Printer className="w-4 h-4" /> Print</Button>
          </div>
          <div className="mb-4 no-print"><SearchBar value={custSearch} onChange={setCustSearch} placeholder="Search customers..." /></div>
          <div id="report-customers">
            <div className="report-header"><h1>{businessName}</h1><p>Customer Report — {formatDate(new Date())}</p></div>
            <table><thead><tr><th>Customer</th><th>Phone</th><th>Card</th><th className="text-right">Spent</th><th className="text-right">Visits</th><th className="text-right">Points</th></tr></thead><tbody>
              {filteredCustomers.map((c) => (
                <tr key={c._id}><td style={{ fontWeight: 700 }}>{c.name}</td><td>{c.phone || "—"}</td><td className="font-mono">{c.loyaltyCardNumber || "—"}</td><td className="text-right">{formatCurrency(c.totalSpent || 0)}</td><td className="text-right">{c.visitCount || 0}</td><td className="text-right text-yellow" style={{ fontWeight: 700 }}>{c.loyaltyPoints || 0}</td></tr>
              ))}
            </tbody></table>
            <ReportFooter businessName={businessName} />
          </div>
        </div>
      )}
    </div>
  );
};